# Use a base image for the build
FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml and src directory
COPY pom.xml .
COPY src ./src

# Build the application
RUN mvn clean package -DskipTests

# Use a new stage to build the final image
FROM openjdk:17-jdk-slim AS runtime

# Set the working directory
WORKDIR /app
RUN ls -l /app/target
# Copy the JAR file from the builder stage
COPY --from=build /app/target/microservice-1-0.0.1-SNAPSHOT.jar microservice-1.jar

# Change the exposed port
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "microservice-1.jar"]
