# Stage 1: Build the application
FROM maven:3.8.6-openjdk-11 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

RUN ls -l /app 

# Stage 2: Create the runtime image
FROM openjdk:11-jre-slim

# Copy the JAR from the build stage (update the path as needed)
COPY --from=build /app/target/com.0.0.1-SNAPSHOT.jar /microservice-1.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/microservice-1.jar"]
